// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mishvets/WeatherForecast/worker (interfaces: TaskDistributor)
//
// Generated by this command:
//
//	mockgen --package mockworker --destination worker/mock/distributor.go github.com/mishvets/WeatherForecast/worker TaskDistributor
//

// Package mockworker is a generated GoMock package.
package mockworker

import (
	context "context"
	reflect "reflect"

	asynq "github.com/hibiken/asynq"
	worker "github.com/mishvets/WeatherForecast/worker"
	gomock "go.uber.org/mock/gomock"
)

// MockTaskDistributor is a mock of TaskDistributor interface.
type MockTaskDistributor struct {
	ctrl     *gomock.Controller
	recorder *MockTaskDistributorMockRecorder
	isgomock struct{}
}

// MockTaskDistributorMockRecorder is the mock recorder for MockTaskDistributor.
type MockTaskDistributorMockRecorder struct {
	mock *MockTaskDistributor
}

// NewMockTaskDistributor creates a new mock instance.
func NewMockTaskDistributor(ctrl *gomock.Controller) *MockTaskDistributor {
	mock := &MockTaskDistributor{ctrl: ctrl}
	mock.recorder = &MockTaskDistributorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskDistributor) EXPECT() *MockTaskDistributorMockRecorder {
	return m.recorder
}

// DistributeTaskCreateWeatherData mocks base method.
func (m *MockTaskDistributor) DistributeTaskCreateWeatherData(ctx context.Context, payload *worker.PayloadCreateWeatherData, optd ...asynq.Option) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, payload}
	for _, a := range optd {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DistributeTaskCreateWeatherData", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DistributeTaskCreateWeatherData indicates an expected call of DistributeTaskCreateWeatherData.
func (mr *MockTaskDistributorMockRecorder) DistributeTaskCreateWeatherData(ctx, payload any, optd ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, payload}, optd...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DistributeTaskCreateWeatherData", reflect.TypeOf((*MockTaskDistributor)(nil).DistributeTaskCreateWeatherData), varargs...)
}

// DistributeTaskSendNotifyEmails mocks base method.
func (m *MockTaskDistributor) DistributeTaskSendNotifyEmails(ctx context.Context, payload *worker.PayloadSendNotifyEmails, opts ...asynq.Option) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, payload}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DistributeTaskSendNotifyEmails", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DistributeTaskSendNotifyEmails indicates an expected call of DistributeTaskSendNotifyEmails.
func (mr *MockTaskDistributorMockRecorder) DistributeTaskSendNotifyEmails(ctx, payload any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, payload}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DistributeTaskSendNotifyEmails", reflect.TypeOf((*MockTaskDistributor)(nil).DistributeTaskSendNotifyEmails), varargs...)
}

// DistributeTaskSendVerifyEmail mocks base method.
func (m *MockTaskDistributor) DistributeTaskSendVerifyEmail(ctx context.Context, payload *worker.PayloadSendVerifyEmail, optd ...asynq.Option) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, payload}
	for _, a := range optd {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DistributeTaskSendVerifyEmail", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DistributeTaskSendVerifyEmail indicates an expected call of DistributeTaskSendVerifyEmail.
func (mr *MockTaskDistributorMockRecorder) DistributeTaskSendVerifyEmail(ctx, payload any, optd ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, payload}, optd...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DistributeTaskSendVerifyEmail", reflect.TypeOf((*MockTaskDistributor)(nil).DistributeTaskSendVerifyEmail), varargs...)
}
